# Generated by Django 4.0.3 on 2022-05-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('nom_joueur', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('club', models.CharField(max_length=100)),
            ],
        ),
    ]
