# Generated by Django 4.0.3 on 2022-05-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_club', models.CharField(max_length=100)),
                ('classement_club', models.CharField(max_length=100)),
                ('ligue_club', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('nom_joueur', models.CharField(max_length=100)),
                ('poste', models.CharField(default=None, max_length=100)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.club')),
            ],
        ),
    ]
