# Generated by Django 4.0.3 on 2022-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_club', models.CharField(max_length=100)),
                ('ligue_club', models.CharField(max_length=100)),
                ('classement_club', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='foot',
            name='date_naissance',
        ),
    ]
