# Generated by Django 4.0.3 on 2022-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club_remove_foot_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='foot',
            name='poste',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
