# Generated by Django 4.0.3 on 2022-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_coach_foot_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foot',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
